### ISSUE TITLE
Connection to 3259/10 (http protocol) suddenly stopped working

### ISSUE THREAD

**Issue by ronaldt80** [rgerganov/py-air-control#100]
I have been using this library (v. 2.2) for a few years without issues; since one week however I can no longer connect to my 2 airpurifiers (both http / 3259/10). Running airctrl (either directly on raspberry pi or through the home assistant integration I use) results in the following error. Did anyone else experience this? 

```
airctrl --ipaddr 192.168.40.xxx --protocol http
Exchanging secret key with the device ...
Traceback (most recent call last):
  File "/home/pi/.local/bin/airctrl", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/pyairctrl/airctrl.py", line 201, in main
    c = HTTPAirCli(device["ip"])
  File "/home/pi/.local/lib/python3.7/site-packages/pyairctrl/airctrl.py", line 116, in __init__
    super().__init__(HTTPAirClient(host, debug))
  File "/home/pi/.local/lib/python3.7/site-packages/pyairctrl/http_client.py", line 111, in __init__
    self.load_key()
  File "/home/pi/.local/lib/python3.7/site-packages/pyairctrl/http_client.py", line 159, in load_key
    self._get_key()
  File "/home/pi/.local/lib/python3.7/site-packages/pyairctrl/http_client.py", line 122, in _get_key
    with urllib.request.urlopen(req) as response:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500:
```

**Comment by ronaldt80** [comment]
closed per #[https://github.com/GeorgeSG/philips_airpurifier_http/issues/13](url)
