### ISSUE TITLE
About initial wifi setup with Pi

### ISSUE THREAD

**Issue by lhttony** [rgerganov/py-air-control#19]
Hello, 
If my air purifier is already connected to my home network through the Air Matters app, do I still need to do the wifi setup ?

because I'm getting the error when I try to "airctrl ipaddr" it :
ConnectionRefusedError: [Errno 111] Connection refused

So I think I'd need to do the Wifi setup again and without the Air Matters app right ?

**Comment by rgerganov** [comment]
No, you don't need to go through the wifi setup if the purifier is already connected to your network. Just find its IP address and then you can use the app.

**Comment by lhttony** [comment]
Thanks for you reply, can you give me some hints on below error ?
I have checked the IP is correct, and you may note about my setup:
- The device was joining my network from my iphone with Philips's Air Matters app, and the device could be controlled there.
- Below "airctrl 192.168.1.3" testing is done on a raspberry PI on the same home network,
and I'm trying to rely on this py-air-control with Homebridge to control the device in Apple's Home app, 


Error logs :
hoobs@hoobs:/var/lib/homebridge $ airctrl 192.168.1.3
Exchanging secret key with the device ...
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hoobs/.local/bin/airctrl", line 10, in <module>
    sys.exit(main())
  File "/home/hoobs/.local/lib/python3.7/site-packages/airctrl/airctrl.py", line 255, in main
    c.load_key()
  File "/home/hoobs/.local/lib/python3.7/site-packages/airctrl/airctrl.py", line 87, in load_key
    self._get_key()
  File "/home/hoobs/.local/lib/python3.7/site-packages/airctrl/airctrl.py", line 53, in _get_key
    with urllib.request.urlopen(req) as response:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by rgerganov** [comment]
Try to ping the air purifier from your RPi to make sure you have network connectivity.

**Comment by rgerganov** [comment]
Closing this assuming it is a networking issue. Feel free to reopen.
