### ISSUE TITLE
Config error after updating py-air-control

### ISSUE THREAD

**Issue by sidamos** [rgerganov/py-air-control#59]
After upgrading from Python 3.6 to 3.7, py-air-control did not find Python anymore. So I decided to upgrade py-air-control to the newest version, hoping that this will fix the problem.
After updating py-air-control, it finds Python again, but now I have a different problem:

```
$ /home/mythtv/.local/bin/airctrl --ipaddr 192.168.0.34 --pwr 1
Traceback (most recent call last):
  File "/home/mythtv/.local/bin/airctrl", line 8, in <module>
    sys.exit(main())
  File "/home/mythtv/.local/lib/python3.7/site-packages/pyairctrl/airctrl.py", line 444, in main
    c = HTTPAirCli(device["ip"])
  File "/home/mythtv/.local/lib/python3.7/site-packages/pyairctrl/airctrl.py", line 100, in __init__
    self._client = HTTPAirClient(host, debug)
  File "/home/mythtv/.local/lib/python3.7/site-packages/pyairctrl/http_client.py", line 108, in __init__
    self.load_key()
  File "/home/mythtv/.local/lib/python3.7/site-packages/pyairctrl/http_client.py", line 148, in load_key
    config.read(fpath)
  File "/usr/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.7/configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/mythtv/.pyairctrl', line: 1
```

Seems like the config is not compatible anymore. Can I fix that without re-pairing?

**Comment by sidamos** [comment]
I was able to fix it by changing .pyairctrl like this:
```
[keys]
192.168.0.34 = key from old config
```
